project:
  type: website
  output-dir: _site
  resources:
    - CNAME
website:
  title: "Ramon's journal"
  description: "AI research scientist"
  site-url: https://onalix.com
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Journal"
        href: journal.qmd
      - icon: github
        href: https://github.com/onalix
format:
  html:
    theme: litera
    css: styles.css
 