baseURL = 'https://onalix.com/'
languageCode = 'en-us'
title = "Ramon's journal"
theme = 'PaperMod'
ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$" ]

[markup.goldmark.renderer]
  unsafe= true
[markup.goldmark.extensions.passthrough]
  enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  block = [['$$', '$$']]
  inline = [['$', '$']]
[params]
  math = true
  defaultTheme = 'light'
  disableThemeToggle = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowToc = true
  TocOpen = false
[params.profileMode]
  enabled = true
  imageUrl = "/images/ramon_profile.png"
  imageTitle = "Ramon N. Rayas"
  imageWidth = 150
  imageHeight = 150
  title = "Ramon N. Rayas"
  subtitle = "ML engineer and data scientist."
[[params.profileMode.buttons]]
  name = "Continue reading"
  url = "/posts" 
[[params.profileMode.buttons]]
  name = "Search archive"
  url = "/archive"
[[params.socialIcons]]
  name = "Github"
  url = "https://github.com/onalix"
[params.editPost]
  URL = "https://github.com/onalix/onalix/blob/main/content"
  Text = "Suggest changes"
  appendFilePath = true
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]
[outputs]
  home = ["HTML", "RSS", "JSON"]
